{% set name = "types-enum34" %}
{% set version = "1.1.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-enum34-{{ version }}.tar.gz
  sha256: fb220b3cf234f500730a817d46c432b374a0d8346a8ae4adecbf85bf8a764f6b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/enum-python2-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for enum34
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
